# GitHub action to test arduino sketch compiles

name: Arduino Sketch Compiles

# Controls when the action will run. 
on:
  # Trigger workflow when arduino sketch changes
  push:
    # branches: [ main ]
    paths:
      - 'arduino-uno/arduino/**'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "arduino-sketch-compile-test"
  arduino-sketch-compile-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive

      # install arduino cli
      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

      # install arduino board
      - name: Install arduino-cli cores
        run: |
          ./bin/arduino-cli core install arduino:avr
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core list

      # link arduino libraries folder to additional-libraries folder
      - name: link libraries folder
        run: |
          mkdir ~/Arduino
          ln -s $PWD/additional-libraries ~/Arduino/libraries

      # compile sketch
      - name: Compile sketch
        run: ./bin/arduino-cli compile --fqbn arduino:avr:uno arduino-uno/arduino/vl53l0x-distance-sensor/vl53l0x-distance-sensor.ino
